version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookmark
    networks:
    - freecodecamp
  test-db:
    image: postgres:latest
    ports: 
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookmark
    networks:
    - freecodecamp
networks:
  freecodecamp: